### ISSUE TITLE
May I take over the `twisty` npm package name?

### ISSUE THREAD

**Issue by lgarron** [Aehmlo/twisty#1]
Hi there!

I wrote https://github.com/cubing/twisty.js starting back in 2011, and am reworking it to be a proper modern library ([here](https://github.com/cubing/alg.cubing.net/tree/v2/twisty)). I didn't reserve the name `twisty` on `npm` originally, but it seems publishing on `npm` is the way to go these days.

Since you don't seem to be working on this package, any chance you'd be willing to cede the `twisty` package name so that I could use it? It's your right to keep it, of course, but I thought I'd ask.

Thanks,
»Lucas

**Comment by Aehmlo** [comment]
Sure! I'm planning on coming back to this project, but I'm likely going to use Rust this time around, so there's no reason for me to keep the name on npm.

One condition — make sure you make the library a shining example of best practices and quality code. Gotta honor the `twisty` name and all.

I've added you as an owner, so you're in the driver's seat now. I'd appreciate if you make the next version a semver-compliant breaking change.

Best of luck!
